<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Urify\Form\UrifyForm $form
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()
    ->appendStylesheet($assetUrl('css/urify.css', 'Urify'));

$this->htmlElement('body')->appendAttribute('class', 'urify urify-index');
?>

<?= $this->pageTitle($translate('Prepare'), 1, $translate('Urify')) ?>

<div id="page-actions">
    <button type="submit" form="urify-form"><?= $escape($translate('Submit')) ?></button>
</div>

<nav class="section-nav">
    <?= $this->navigation('Laminas\Navigation\Urify')->menu() ?>
</nav>

<div class="block">
    <?= $this->form($form) ?>
</div>
