<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\JobRepresentation[] $jobs
 * @var \Omeka\DataType\Manager $dataTypeManager
 * @var string $baseUrlFiles
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$jobState = $plugins->has('jobState') ? $plugins->get('jobState') : null;
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$easyMeta = $plugins->get('easyMeta');
$translatePlural = $plugins->get('translatePlural');

$hasLog = isset($jobState);
if ($hasLog) {
    $this->headLink()
        ->appendStylesheet($assetUrl('css/job.css', 'Log'))
        ->appendStylesheet($assetUrl('css/log.css', 'Log'));
    $this->headScript()
        ->appendFile($assetUrl('js/job.js', 'Log'), 'text/javascript', ['defer' => 'defer'])
        ->appendFile($assetUrl('js/log.js', 'Log'), 'text/javascript', ['defer' => 'defer']);
}

$this->headLink()
    ->appendStylesheet($assetUrl('css/urify.css', 'Urify'));

$this->htmlElement('body')->appendAttribute('class', 'urify browse');

$hasAdvancedSearch = class_exists('AdvancedSearch\Module', false);
$mainCustomVocabs = $easyMeta->dataTypeMainCustomVocabs();

$baseUrlProperty = $hasAdvancedSearch
    ? null
    : $url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['property[0][property]' => '{property}', 'property[0][type]' => 'ex']]);
?>

<?= $this->pageTitle($translate('Browse'), 1, $translate('Urify')) ?>

<nav class="section-nav">
    <?= $this->navigation('Laminas\Navigation\Urify')->menu() ?>
</nav>

<?php if ($jobs): ?>

<?php $this->trigger('view.browse.before'); ?>

<div class="block">
    <table class="tablesaw batch-edit" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th>
                    <?= $escape($translate('Name')) ?>
                </th>
                <th><?= $escape($translate('Data type')) ?></th>
                <th><?= $escape($translate('Properties')) ?></th>
                <th><?= $escape($translate('Date')) ?></th>
                <th><?= $escape($translate('Query')) ?></th>
                <th><?= $escape($translate('Status/Log/Params')) ?></th>
                <th><?= $escape($translate('Spreadsheet')) ?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($jobs as $job):
                $stateHtml = $jobState($job, ['output' => 'html']);
                $jobArgs = $job->args();
                $spreadsheet = $jobArgs['spreadsheet'] ?? null;
                $properties = $jobArgs['properties'] ?? [];
                $query = $jobArgs['query'] ?? [];
                $dataType = $jobArgs['datatype'] ?? null;
                if ($hasAdvancedSearch) {
                    $dataTypes = [];
                    $valueTypes = $jobArgs['value_types'] ?? [];
                    if (in_array('literal', $valueTypes)) $dataTypes[] = 'literal';
                    if (in_array('uri', $valueTypes)) $dataTypes[] = 'uri';
                    if (in_array('specified', $valueTypes)) $dataTypes[] = $dataType;
                    if (in_array('custom_vocab_literal', $valueTypes)) $dataTypes = array_merge($dataTypes, array_values(array_filter($mainCustomVocabs, fn ($v) => $v === 'literal')));
                    if (in_array('custom_vocab_uri', $valueTypes)) $dataTypes = array_merge($dataTypes, array_values(array_filter($mainCustomVocabs, fn ($v) => $v === 'uri')));
                    $dataTypes  = array_unique($dataTypes);
                    $urlProperty = $url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['filter' => ['field' => $properties, 'type' => 'dtp', 'val' => $dataTypes]]]);
                } else {
                    // TODO Improve standard search query without module Advanced Search. Most of the time, there is only one property.
                    $urlProperty = strtr($baseUrlProperty, ['{property}' => reset($properties)]);
                }
                ?>
            <tr>
                <td>
                    <?= $hyperlink($jobArgs['label'] ?: sprintf('Job #%d', $job->id()), $url('admin/urify/id', ['id' => $job->id(), 'action' => 'show'])) ?>
                </td>
                <td><?= $dataTypeManager->has($dataType) ? $escape($translate($dataTypeManager->get($dataType)->getLabel())) : $escape($dataType) ?></td>
                <td>
                    <ul class="property-counts">
                        <?php foreach ($properties as $property): ?>
                        <li><dl>
                            <dt><span class="property"><?= $hyperlink(sprintf($translate('%1$s : %2$s'), $translate($easyMeta->vocabularyLabel(strtok($property, ':'))), $translate($easyMeta->propertyLabel($property))), $urlProperty) ?></span></dt>
                            <dd><span class="counts count-values"><?= $escape(sprintf($translatePlural('%d value', '%d values', $v = count($jobArgs['results'][$property] ?? [])), $v)) ?></span></dd>
                            <dd><span class="counts count-uris"><?= $escape(sprintf($translatePlural('%d uri', '%d uris', $v = array_sum(array_map(fn ($v) => count($v['uris']), $jobArgs['results'][$property] ?? []))), $v)) ?></span></dd>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </td>
                <td><?= $job->started() ? $i18n->dateFormat($job->started(), 'medium', 'medium') : $escape($translate('Not started')) ?></td>
                <td><?= $query ? $hyperlink($translate('Yes'), $url('admin/default', ['controller' => 'item'], ['query' => $query])) : '' ?></td>
                <td>
                    <div class="log-job job-status" data-job-id="<?= $job->id() ?>">
                        <?php if ($stateHtml): ?>
                            <?= $jobState($job, ['output' => 'html', 'include_job_status' => true]) ?>
                            <?= $hyperlink($translate('Logs'), $hasLog
                                ? $url('admin/default', ['controller' => 'log'], ['query' => ['job_id' => $job->id()]])
                                : $url('admin/id', ['controller' => 'job', 'action' => 'log', 'id' => $job->id()])) ?>
                        <span class="log-job-param"><em><?= $hyperlink($translate('Parameters'), $url('admin/id', ['controller' => 'job', 'action' => 'show', 'id' => $job->id()])) ?></em></span>
                        <?php else: ?>
                        <span class="log-job-status job-status-label">
                            <?= $hyperlink($translate($job->statusLabel()), $hasLog
                                ? $url('admin/default', ['controller' => 'log'], ['query' => ['job_id' => $job->id()]])
                                : $url('admin/id', ['controller' => 'job', 'action' => 'log', 'id' => $job->id()])) ?>
                        </span>
                        <span class="log-job-param"><em><?= $hyperlink($translate('Parameters'), $url('admin/id', ['controller' => 'job', 'action' => 'show', 'id' => $job->id()])) ?></em></span>
                        <?php endif; ?>
                    </div>
                </td>
                <td><?= $spreadsheet ? $hyperlink($spreadsheet, $baseUrlFiles . '/result/urify/' . $spreadsheet) : '' ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php $this->trigger('view.browse.after'); ?>

<?php else: ?>

<div class="block no-resources no-files">
    <p>
        <?= $escape($translate('No urification.')) ?>
    </p>
</div>

<?php endif; ?>
