<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\JobRepresentation $job
 * @var array $results
 * @var string $baseUrlFiles
 * @var \Urify\Form\UrifyMapperForm|null $form
 * @var bool $hasMapper
 * @var string|null $updateMode
 * @var string|null $updateMapper
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$jobState = $plugins->has('jobState') ? $plugins->get('jobState') : null;
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$easyMeta = $plugins->get('easyMeta');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$hasLog = isset($jobState);
if ($hasLog) {
    $this->headLink()
        ->appendStylesheet($assetUrl('css/job.css', 'Log'))
        ->appendStylesheet($assetUrl('css/log.css', 'Log'));
    $this->headScript()
        ->appendFile($assetUrl('js/job.js', 'Log'), 'text/javascript', ['defer' => 'defer'])
        ->appendFile($assetUrl('js/log.js', 'Log'), 'text/javascript', ['defer' => 'defer']);
}

$this->headLink()
    ->appendStylesheet($assetUrl('css/common-dialog.css', 'Common'))
    ->appendStylesheet($assetUrl('css/urify.css', 'Urify'));
$this->headScript()
    ->appendFile($assetUrl('js/common-dialog.js', 'Common'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/urify.js', 'Urify'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'urify show');

$jobArgs = $job->args();
$results = $jobArgs['results'] ?? [];
$baseUrlItem = $url('admin/default', ['controller' => 'item', 'action' => 'browse']);
$jobQuery = $jobArgs['query'] ?? [];

$hasError = $job->status() === \Omeka\Entity\Job::STATUS_ERROR;
?>

<?= $this->pageTitle($jobArgs['label'] ?: sprintf($translate('Job #%d'), $job->id()), 1, $translate('Urify')) ?>

<nav class="section-nav">
    <?= $this->navigation('Laminas\Navigation\Urify')->menu() ?>
</nav>

<div class="block">
    <p><?= $job->started() ? $i18n->dateFormat($job->started(), 'medium', 'medium') : $translate('Not started') ?></p>
    <?php if ($v = ($jobState && $jobState($job))): ?>
    <?= $jobState($job, ['output' => 'html']) ?>
    <?php endif; ?>
    <p>
        <?= $v ? '' : sprintf('%s.', $translate($job->statusLabel())) ?>
        <?php if ($spreadsheet = $jobArgs['spreadsheet'] ?? null): ?>
        <?= sprintf($escape($translate('See %1$sspreadsheet%2$s.')), sprintf('<a href="%s">', $baseUrlFiles . '/result/urify/' . $spreadsheet), '</a>') ?>
        <?php endif; ?>
        <?= sprintf($hasError
            ? $escape($translate('See errors in job %1$slogs%2$s and %3$sparams%2$s.'))
            : $escape($translate('See job %1$slogs%2$s and %3$sparams%2$s.')),
            class_exists('Log\Module', false)
                ? sprintf('<a href="%1$s">', $url('admin/default', ['controller' => 'log'], ['query' => ['job_id' => $job->id()]]))
                : sprintf('<a href="%1$s" target="_blank">', $url('admin/id', ['controller' => 'job', 'action' => 'log', 'id' => $job->id()])),
            '</a>',
            '<a href="' . $job->adminUrl() . '">'
        ) ?>
    </p>
    <?php if ($jobQuery): ?>
    <p>
        <?php // TODO Use the filter of the omeka input element Query. ?>
        <?= sprintf($escape($translate('The job was run on resources matching this %1$squery%2$s.')), sprintf('<a href="%s">', $escapeAttr($url('admin/default', ['controller' => 'item'], ['query' => $jobQuery]))), '</a>') ?>
        <?= sprintf($escape($translate('Warning: this query is not included in the links below, but is used when urifying values.'))) ?>
    </p>
    <?php endif; ?>
</div>

<?php if ($results): ?>

<div class="block"
    data-msg-apply="<?= $jobQuery
        ? $escapeAttr(nl2br($translate(<<<'TXT'
            Replace value: {value}
            with label: {label}
            and uri: {uri}
            for the property: {property}
            of queried resources?
            Edit the label if wanted or remove it to keep the current one:
            TXT)))
        : $escapeAttr(nl2br($translate(<<<'TXT'
            Replace value: {value}
            with label: {label}
            and uri: {uri}
            for the property: {property}
            of all resources?
            Edit the label if wanted or remove it to keep the current one:
            TXT))) ?>"
    data-msg-confirm-batch="<?= $jobQuery
        ? $escapeAttr(nl2br($translate(<<<'TXT'
            Apply the mapper:
            {mapper}
            to queryied resources with values fetched from uri:
            {uri}
            TXT)))
        : $escapeAttr(nl2br($translate(<<<'TXT'
            Apply the mapper:
            {mapper}
            to all resources with values fetched from uri:
            {uri}
            TXT))) ?>"
    data-url-urify="<?= $escapeAttr($url('admin/urify/id', ['action' => 'apply', 'id' => $job->id()])) ?>"
    data-job-id="<?= $job->id() ?>"
    data-has-query="<?= (int) !empty($jobQuery) ?>">

    <?php if ($form): ?>
    <div class="mapper-form">
       <?= $this->form($form) ?>
    </div>
    <?php endif; ?>

    <?php foreach ($results as $propertyTerm => $result): ?>

    <dl>
        <dt><?= sprintf($escape($translate('Property: %1$s%2$s : %3$s%4$s')), sprintf('<a href="%s">', $escapeAttr($url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['property[0][property]' => $propertyTerm, 'property[0][type]' => 'ex']]))), $translate($easyMeta->vocabularyLabel(strtok($propertyTerm, ':'))), $translate($easyMeta->propertyLabel($propertyTerm)), '</a>') ?></dt>
        <dd><?= sprintf($escape($translate('Number of values: %d.')), count($result)) ?></dd>
        <dd><?= sprintf($escape($translate('Number of uris: %d.')), array_sum(array_map(fn ($v) => count($v['uris']), $result))) ?></dd>
    </dl>

    <table class="tablesaw batch-edit" data-tablesaw-mode="stack" data-property-term="<?= $escapeAttr($propertyTerm) ?>">
        <thead>
            <tr>
                <th><?= $escape($translate('Value')) ?></th>
                <th><?= $escape($translate('Uris')) ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($result as $data): ?>
            <tr class="urify-value-uris">
                <td>
                    <div><?= $hyperlink($data['label'], $baseUrlItem . '?' . http_build_query(['property' => [['property' => $propertyTerm, 'type' => 'eq', 'text' => $data['label']]]], '', '&', PHP_QUERY_RFC3986), ['class' => 'value-to-urify']) ?></div>
                    <div><?= sprintf($escape($translate('First resources on a total of %d')), $data['count']) ?>
                        <ul class="list-resource-ids">
                            <?php foreach ($data['resources'] ?? [] as $resourceId): ?>
                            <li><?= $hyperlink(sprintf($escape($translate('#%d')), $resourceId), $baseUrlItem . '/' . $resourceId) ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </td>
                <td>
                       <?php if (!empty($data['uris'])): ?>
                    <ul class="list-uris">
                        <?php foreach ($data['uris'] as $uri => $label): ?>
                        <li class="uri-label">
                            <button type="button" class="apply-uri-to-values" title="<?= $v = $escapeAttr($jobQuery ? $translate('Update queried resources with this uri') : $translate('Update all resources with this uri')) ?>"aria-label="<?= $v ?>"><span class="fas fa-check"></span></button>
                            <span class="uri-label"><?= $hyperlink($label ?: $uri, $uri) ?></span>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php endforeach; ?>

    <?php // TODO Export. ?>
</div>

<?php else: ?>

<div class="block no-resources no-files">
    <p>
        <?= $escape($translate('No results.')) ?>
    </p>
</div>

<?php endif; ?>
